#spring:
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 192.168.30.128:8848
#  application:
#      name: gulimall-coupon
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: root
#    url: jdbc:mysql://192.168.30.128:3306/gulimall_sms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
#mybatis-plus:
#  global-config:
#    db-config:
#      id-type: auto
#  mapper-locations: classpath:/mapper/**/*.xml
#server:
#  port: 10003
