server:
  port: 20000
  servlet:
    session:
      timeout: 30m
#
#  servlet:
#    session:
#      timeout: 30m

spring:
  application:
    name: gulimall-auth-server
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.30.128:8848

    sentinel:
      transport:
        #配置sentinel dashboard地址
        dashboard: localhost:8333

  redis:
    host: 192.168.30.128
    port: 6379

#开启feign对sentinel的支持
feign:
  sentinel:
    enabled: true
  thymeleaf:
    cache: false
  session:
    store-type: redis

#暴露所有端点
management:
  endpoints:
    web:
      exposure:
        include: '*'



